/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clase.tramitefinalizado.ArbolAtendidos;
import clase.tramitefinalizado.NodoA;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public final class ListaTramitesFinalizadosIU extends javax.swing.JFrame {

    /**
     * Creates new form ListaTramitesFinalizadosIU
     */
    private ArbolAtendidos arbol;
    private DefaultTableModel modeloTabla;
    private NodoA raiz;
    public ListaTramitesFinalizadosIU() {
    }
    
    public ListaTramitesFinalizadosIU(ArbolAtendidos arbol) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        this.arbol = arbol;
        raiz =arbol.getRaizA();
        modeloTabla = new DefaultTableModel();
        this.TablaTramitesTerminados.setModel(modeloTabla);
        modeloTabla.addColumn("id_exp");
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("dependencia");
        modeloTabla.addColumn("fecha inicio");
        modeloTabla.addColumn("fecha termino");
        modeloTabla.addColumn("documentos");
        modeloTabla.addColumn("estado");
        InorderModeloTabla(raiz);
        
    }
    
    private void InorderModeloTabla(NodoA raiz){
        if(raiz !=null){
            InorderModeloTabla(raiz.getIzq());
            System.out.println(",("+raiz.getTram().getExp().getId()+"),");
            String[] fila = new String[8];
            fila[0] = String.valueOf(raiz.getTram().getExp().getId());
            fila[1] = String.valueOf(raiz.getTram().getExp().getInter().getNombre());
            fila[2] = String.valueOf(raiz.getTram().getExp().getInter().getDNI());
            fila[3] = String.valueOf(raiz.getTram().getDependencias());
            fila[4] = String.valueOf(raiz.getTram().getH_inicio());
            fila[5] = String.valueOf(raiz.getTram().getH_final());
            fila[6] = String.valueOf(raiz.getTram().isDocs());
            fila[7] = String.valueOf(raiz.getTram().getEstado());
            modeloTabla.addRow(fila);
            InorderModeloTabla(raiz.getDer());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTramitesTerminados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaTramitesTerminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaTramitesTerminados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaTramitesFinalizadosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaTramitesFinalizadosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaTramitesFinalizadosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaTramitesFinalizadosIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaTramitesFinalizadosIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaTramitesTerminados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
