/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clase.expediente.ColaExp;
import clase.expediente.Expediente;
import clase.expediente.NodoExp;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariel
 */
public class ListaExpedientesIU extends javax.swing.JFrame {

    /**
     * Creates new form ListaExpedientesIU
     */
    private DefaultTableModel modeloTabla;
    private ColaExp ColaExpedientes;
    private Image icon;
    public ListaExpedientesIU() {
    }
    
    public ListaExpedientesIU(ColaExp cola) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //icon = new ImageIcon(getClass().getResource("/folder/logo2_1.png")).getImage();
        //setIconImage(icon);
        this.ColaExpedientes = cola;
        modeloTabla = new DefaultTableModel();
        this.TablaExpedientes.setModel(modeloTabla);
        modeloTabla.addColumn("PRIORIDAD");
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("ASUNTO");
        modeloTabla.addColumn("DOC EXP");
        modeloTabla.addColumn("FECHA DE INGRESO");
        modeloTabla.addColumn("NOMBRES");
        modeloTabla.addColumn("TIPOS");
        moverArregloAModeloTabla();
        
        
    }
    private void moverArregloAModeloTabla(){
        // Recuperar la lista de Alumno
        
        for (int i =1 ; i <=ColaExpedientes.getCuenta(); i++) {
            Expediente aux = ColaExpedientes.iesimo(i);
            String[] fila = new String[7];
            fila[0] = String.valueOf(aux.getPrioridad());
            fila[1] = String.valueOf(aux.getId());
            fila[2] = String.valueOf(aux.getAsunto());
            fila[3] = String.valueOf(aux.isDocumento());
            fila[4] = String.valueOf(aux.getFechaingreso());
            fila[5] = String.valueOf(aux.getInter().getNombre());
            fila[6] = String.valueOf(aux.getInter().getTipo());
            modeloTabla.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaExpedientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COLA DE EXPEDIENTES");

        TablaExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaExpedientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaExpedientesIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaExpedientesIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaExpedientesIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaExpedientesIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaExpedientesIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaExpedientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
