/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import clase.dependencias.*;
import javax.swing.table.DefaultTableModel;
import clase.expediente.ColaExp;
import clase.expediente.Expediente;
import clase.expediente.NodoExp;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Sebastián
 */
public class ListaPilaHistoriaIU extends javax.swing.JFrame {

    /**
     * Creates new form ListaPilaHistoriaIU
     */
    
    private Pila PilaDep;
    private DefaultTableModel modeloTabla;
    private Image icon;
    
    public ListaPilaHistoriaIU() {
        initComponents();
        
    }
    
    public ListaPilaHistoriaIU(Pila pila) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        icon = new ImageIcon(getClass().getResource("/folder/logo2_1.png")).getImage();
        setIconImage(icon);
        this.PilaDep = pila;
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("DEPENDENCIA");
        modeloTabla.addColumn("FECHA CAMBIO");
        jTable2.setModel(modeloTabla);
        moverArregloAModeloTabla();
    }
    
    private void moverArregloAModeloTabla(){
        modeloTabla.setRowCount(0);
        if (PilaDep == null || PilaDep.isEmpty()) {
            // Opcional: mostrar un mensaje si no hay historial
            JOptionPane.showMessageDialog(this, "No hay historial de cambios para mostrar.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for (int i = 0; i < PilaDep.contar(); i++) {
            NodoDep NodoActual = PilaDep.isesimo(i);
            if (NodoActual != null) {
                String[] fila = new String[2];
                fila[0] = String.valueOf(NodoActual.getDependenciaActual());
                fila[1] = String.valueOf(NodoActual.getFechaCambio());
                modeloTabla.addRow(fila);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEPENDENCIAS");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPilaHistoriaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPilaHistoriaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPilaHistoriaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPilaHistoriaIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pila pilaDePrueba = new Pila();
                pilaDePrueba.push("DepA", "01-01-2023 10:00:00");
                pilaDePrueba.push("DepB", "02-01-2023 11:30:00");
                pilaDePrueba.push("DepC", "03-01-2023 15:45:00");
                
                new ListaPilaHistoriaIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
